export const MEMBER_GET_REQUEST = 'MEMBER_GET_REQUEST';
export const MEMBER_GET_SUCCESS = 'MEMBER_GET_SUCCESS';
export const MEMBER_GET_FAILURE = 'MEMBER_GET_FAILURE';

export const MEMBER_INSERT_REQUEST = 'MEMBER_INSERT_REQUEST';
export const MEMBER_INSERT_SUCCESS = 'MEMBER_INSERT_SUCCESS';
export const MEMBER_INSERT_FAILURE = 'MEMBER_INSERT_FAILURE';

export const MEMBER_UPDATE_REQUEST = 'MEMBER_UPDATE_REQUEST';
export const MEMBER_UPDATE_SUCCESS = 'MEMBER_UPDATE_SUCCESS';
export const MEMBER_UPDATE_FAILURE = 'MEMBER_UPDATE_FAILURE';

export const MEMBER_DELETE_REQUEST = 'MEMBER_DELETE_REQUEST';
export const MEMBER_DELETE_SUCCESS = 'MEMBER_DELETE_SUCCESS';
export const MEMBER_DELETE_FAILURE = 'MEMBER_DELETE_FAILURE';